[book]
authors = ["kmaitreys"]
language = "en"
src = "src"
title = "kappa: A Primer on Dust Opacities in the ISM"

[build]
build-dir = "../book"

[output.html]
site-url = "/books/kappa"
theme = "../theme"
additional-css = ["../theme/book.css"]
fold = { enable = true, level = 5 }
git-repository-url = "https://github.com/ProsiaLAB/kappa"
git-repository-icon = "fa-github"
