name: Deploy Books to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install mdBook
      run: |
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.37/mdbook-v0.4.37-x86_64-unknown-linux-gnu.tar.gz | tar -xz
        sudo mv mdbook /usr/local/bin/

    - name: Build citrus book
      run: mdbook build citrus

    - name: Build kappa book
      run: mdbook build kappa

    - name: Prepare deployment directory
      run: |
        mkdir -p gh-pages
        cp -r citrus/book gh-pages/citrus
        cp -r kappa/book gh-pages/kappa
        echo '<!DOCTYPE html><html><body><ul><li><a href="citrus/">Citrus</a></li><li><a href="kappa/">Kappa</a></li></ul></body></html>' > gh-pages/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
